"""Generated by dspy.Flex.

You may edit the PREDICTORS dict and the forward()
body between the marker comments below; dspy.Flex parses those regions back
out on the next run.

- __FLEX_SIGNATURE_HASH__ tracks the user's Signature. If you change the
  Signature, Flex regenerates this file, seeding the codegen LM with your
  current code.
- __FLEX_BODY_HASH__ tracks the code body. If you hand-edit the body, Flex
  detects it on the next run, honors your code, and refreshes this hash.

Leave the marker comments and the two hash lines intact.
"""

# __FLEX_SIGNATURE_HASH__: c8d4322c3e040200c9b44ac4ee544a7ab3d2323cde445889240b4eddf7ffe867
# __FLEX_BODY_HASH__: 5df057ebe7c7
# flex_id: StringSignature

import dspy


class StringSignatureModule(dspy.Module):
    """Standalone dspy.Module compiled from the StringSignature signature."""

    # __FLEX_PREDICTORS_BEGIN__
    PREDICTORS = {
        "candidates": dspy.ChainOfThought(dspy.Signature(
            "text: str -> candidate_intents: list[str]",
            (
                "You are helping classify a retail-banking customer message for the BANKING77 dataset.\n"
                "Given the customer's message, propose 4-7 plausible candidate intent labels (snake_case) "
                "from the BANKING77 label set, ordered from most to least likely. Think carefully about what "
                "the customer is ACTUALLY trying to accomplish, not just surface keywords. ALWAYS include "
                "competing/easily-confused labels as candidates so the next stage can disambiguate.\n\n"
                "Critical distinctions and traps:\n"
                "- 'Can I add money in intervals/regularly/automatically/recurring top-up' = automatic_top_up. "
                "  top_up_limits is about MAXIMUM amount limits, NOT scheduling/recurring.\n"
                "- 'A payment came back / was returned / reversed / I got the money back but kept the item' = "
                "  reverted_card_payment?. Refund_not_showing_up is when an EXPECTED refund is MISSING. "
                "  request_refund is when the user wants to REQUEST a refund.\n"
                "- 'I haven't received my PIN/card yet', 'where is my card/PIN' = card_arrival or "
                "  get_physical_card. passcode_forgotten is ONLY for forgotten existing PIN.\n"
                "- 'someone else is using my card / unauthorized use' = compromised_card.\n"
                "- 'lost/stolen' card vs phone matters.\n"
                "- 'pending' (waiting), 'declined' (rejected), 'failed' (transfer failed), 'reverted' (reversed), "
                "  'not recognised' (unknown on statement) are distinct.\n"
                "- 'verify_my_identity' (how to) vs 'unable_to_verify_identity' (it failed) vs "
                "  'why_verify_identity' (why) vs 'verify_source_of_funds'.\n"
                "- 'Is X card / currency / country supported?' = supported_cards_and_currencies / "
                "  visa_or_mastercard / fiat_currency_support / country_support / card_acceptance.\n"
                "- Fee/charge questions = *_charge / *_fee_charged intents.\n\n"
                "The 77 valid labels are:\n"
                "Refund_not_showing_up, activate_my_card, age_limit, apple_pay_or_google_pay, atm_support, automatic_top_up, "
                "balance_not_updated_after_bank_transfer, balance_not_updated_after_cheque_or_cash_deposit, beneficiary_not_allowed, "
                "cancel_transfer, card_about_to_expire, card_acceptance, card_arrival, card_delivery_estimate, card_linking, "
                "card_not_working, card_payment_fee_charged, card_payment_not_recognised, card_payment_wrong_exchange_rate, "
                "card_swallowed, cash_withdrawal_charge, cash_withdrawal_not_recognised, change_pin, compromised_card, "
                "contactless_not_working, country_support, declined_card_payment, declined_cash_withdrawal, declined_transfer, "
                "direct_debit_payment_not_recognised, disposable_card_limits, edit_personal_details, exchange_charge, exchange_rate, "
                "exchange_via_app, extra_charge_on_statement, failed_transfer, fiat_currency_support, get_disposable_virtual_card, "
                "get_physical_card, getting_spare_card, getting_virtual_card, lost_or_stolen_card, lost_or_stolen_phone, "
                "order_physical_card, passcode_forgotten, pending_card_payment, pending_cash_withdrawal, pending_top_up, "
                "pending_transfer, pin_blocked, receiving_money, request_refund, reverted_card_payment?, "
                "supported_cards_and_currencies, terminate_account, top_up_by_bank_transfer_charge, top_up_by_card_charge, "
                "top_up_by_cash_or_cheque, top_up_failed, top_up_limits, top_up_reverted, topping_up_by_card, "
                "transaction_charged_twice, transfer_fee_charged, transfer_into_account, transfer_not_received_by_recipient, "
                "transfer_timing, unable_to_verify_identity, verify_my_identity, verify_source_of_funds, verify_top_up, "
                "virtual_card_not_working, visa_or_mastercard, why_verify_identity, wrong_amount_of_cash_received, "
                "wrong_exchange_rate_for_cash_withdrawal.\n\n"
                "Return ONLY a list of label strings from this set."
            )
        )),
        "analyze": dspy.ChainOfThought(dspy.Signature(
            "text: str, candidate_intents: list[str] -> analysis: str",
            (
                "You are analyzing a BANKING77 customer message to disambiguate among candidate intent labels.\n"
                "For EACH candidate label, write one short sentence: (a) what scenario this label covers, "
                "and (b) whether the customer's message actually matches that scenario, with a yes/no verdict.\n"
                "Be skeptical of surface keyword matches. Focus on the customer's underlying goal.\n\n"
                "Important reminders:\n"
                "- 'in intervals', 'regularly', 'every month', 'recurring', 'automatic' top-up => automatic_top_up, "
                "  NOT top_up_limits (which is about max amount).\n"
                "- 'payment came BACK to my account', 'received the payment back', 'was reversed/returned' after a "
                "  card purchase => reverted_card_payment?. This is NOT Refund_not_showing_up (which is about a "
                "  refund that NEVER ARRIVED) and NOT request_refund (which is asking to GET a refund).\n"
                "- 'haven't received card/PIN' => card_arrival, not passcode_forgotten.\n"
                "- 'someone else used my card' => compromised_card.\n\n"
                "Output a brief structured analysis."
            )
        )),
        "choose": dspy.ChainOfThought(dspy.Signature(
            "text: str, candidate_intents: list[str], analysis: str -> intent: str",
            (
                "You are the final stage of a BANKING77 intent classifier. Given the customer's message, "
                "candidate labels, and a per-candidate analysis, pick the SINGLE best label that captures "
                "the customer's true goal.\n\n"
                "Decision rules to apply:\n"
                "- If the user is asking about scheduling / recurring / interval top-ups, pick automatic_top_up "
                "  (NOT top_up_limits, which is only about maximum amounts).\n"
                "- If the user describes a card payment that came BACK / was reversed / they got the money back "
                "  while keeping the item, pick reverted_card_payment? (NOT Refund_not_showing_up, NOT request_refund).\n"
                "- Refund_not_showing_up is specifically when an EXPECTED refund has NOT arrived.\n"
                "- request_refund is when the user is ASKING to be refunded.\n"
                "- 'haven't received card/PIN yet' => card_arrival; passcode_forgotten is only for forgotten existing PIN.\n"
                "- 'someone else used my card' => compromised_card; 'card lost/stolen' => lost_or_stolen_card.\n"
                "- Distinguish pending / declined / failed / reverted / not_recognised carefully.\n\n"
                "Output ONLY the chosen label verbatim from the candidate list, with no extra words or punctuation."
            )
        )),
    }
    # __FLEX_PREDICTORS_END__

    def __init__(self) -> None:
        super().__init__()
        for _name, _predictor in self.PREDICTORS.items():
            setattr(self, _name, _predictor)

    # __FLEX_FORWARD_BEGIN__
    def forward(self, **inputs):
        valid_labels = {
            "Refund_not_showing_up", "activate_my_card", "age_limit", "apple_pay_or_google_pay",
            "atm_support", "automatic_top_up", "balance_not_updated_after_bank_transfer",
            "balance_not_updated_after_cheque_or_cash_deposit", "beneficiary_not_allowed",
            "cancel_transfer", "card_about_to_expire", "card_acceptance", "card_arrival",
            "card_delivery_estimate", "card_linking", "card_not_working", "card_payment_fee_charged",
            "card_payment_not_recognised", "card_payment_wrong_exchange_rate", "card_swallowed",
            "cash_withdrawal_charge", "cash_withdrawal_not_recognised", "change_pin",
            "compromised_card", "contactless_not_working", "country_support", "declined_card_payment",
            "declined_cash_withdrawal", "declined_transfer", "direct_debit_payment_not_recognised",
            "disposable_card_limits", "edit_personal_details", "exchange_charge", "exchange_rate",
            "exchange_via_app", "extra_charge_on_statement", "failed_transfer", "fiat_currency_support",
            "get_disposable_virtual_card", "get_physical_card", "getting_spare_card",
            "getting_virtual_card", "lost_or_stolen_card", "lost_or_stolen_phone",
            "order_physical_card", "passcode_forgotten", "pending_card_payment",
            "pending_cash_withdrawal", "pending_top_up", "pending_transfer", "pin_blocked",
            "receiving_money", "request_refund", "reverted_card_payment?",
            "supported_cards_and_currencies", "terminate_account", "top_up_by_bank_transfer_charge",
            "top_up_by_card_charge", "top_up_by_cash_or_cheque", "top_up_failed", "top_up_limits",
            "top_up_reverted", "topping_up_by_card", "transaction_charged_twice",
            "transfer_fee_charged", "transfer_into_account", "transfer_not_received_by_recipient",
            "transfer_timing", "unable_to_verify_identity", "verify_my_identity",
            "verify_source_of_funds", "verify_top_up", "virtual_card_not_working",
            "visa_or_mastercard", "why_verify_identity", "wrong_amount_of_cash_received",
            "wrong_exchange_rate_for_cash_withdrawal",
        }

        def normalize(lbl):
            if not isinstance(lbl, str):
                return ""
            s = lbl.strip().strip("'\"`.,;: ").strip()
            if s in valid_labels:
                return s
            low = s.lower()
            for v in valid_labels:
                if v.lower() == low:
                    return v
            # try removing trailing '?' or adding it back
            if s.endswith("?"):
                base = s[:-1]
                for v in valid_labels:
                    if v.lower() == base.lower():
                        return v
            else:
                for v in valid_labels:
                    if v.lower() == (s + "?").lower():
                        return v
            return ""

        text = inputs.get("text", "")

        try:
            cand_pred = self.candidates(text=text)
            raw_cands = cand_pred.candidate_intents or []
        except Exception:
            raw_cands = []

        if isinstance(raw_cands, str):
            raw_cands = [c for c in raw_cands.replace("\n", ",").split(",")]

        cands = []
        for c in raw_cands:
            n = normalize(c)
            if n and n not in cands:
                cands.append(n)

        # Heuristic candidate injection based on strong textual cues, to give the
        # disambiguator a fighting chance even if the candidate stage missed them.
        low_text = text.lower()

        def add(lbl):
            if lbl in valid_labels and lbl not in cands:
                cands.append(lbl)

        # Recurring / scheduled top-up cues
        if any(k in low_text for k in [
            "interval", "intervals", "regularly", "every month", "every week",
            "recurring", "automatic", "automatically", "schedule", "scheduled",
            "set up to add", "set up a top", "standing order", "periodically"
        ]):
            if "top" in low_text or "add money" in low_text or "add funds" in low_text or "deposit" in low_text:
                add("automatic_top_up")

        # Reverted card payment cues
        if any(k in low_text for k in [
            "payment back", "money back into", "received the payment back",
            "came back", "returned to my account", "reversed", "reverted",
            "got my money back", "payment was returned"
        ]):
            add("reverted_card_payment?")
            add("Refund_not_showing_up")
            add("request_refund")

        # Missing refund cues
        if "refund" in low_text and any(k in low_text for k in [
            "haven't received", "not received", "not showing", "where is my refund",
            "still waiting", "no refund"
        ]):
            add("Refund_not_showing_up")

        # Card/PIN not arrived
        if any(k in low_text for k in ["haven't received my card", "card hasn't arrived",
                                        "where is my card", "haven't gotten my card",
                                        "haven't received my pin", "pin hasn't arrived"]):
            add("card_arrival")
            add("get_physical_card")

        if not cands:
            cands = sorted(valid_labels)

        # Cap candidates to keep the chooser focused
        if len(cands) > 12:
            cands = cands[:12]

        try:
            ana_pred = self.analyze(text=text, candidate_intents=cands)
            analysis = ana_pred.analysis or ""
        except Exception:
            analysis = ""

        try:
            chosen = self.choose(text=text, candidate_intents=cands, analysis=str(analysis))
            intent = normalize(chosen.intent)
        except Exception:
            intent = ""

        if not intent:
            intent = cands[0] if cands else "card_not_working"

        return dspy.Prediction(intent=str(intent))
    # __FLEX_FORWARD_END__
