"""Generated by dspy.Flex.

You may edit the PREDICTORS dict and the forward()
body between the marker comments below; dspy.Flex parses those regions back
out on the next run.

- __FLEX_SIGNATURE_HASH__ tracks the user's Signature. If you change the
  Signature, Flex regenerates this file, seeding the codegen LM with your
  current code.
- __FLEX_BODY_HASH__ tracks the code body. If you hand-edit the body, Flex
  detects it on the next run, honors your code, and refreshes this hash.

Leave the marker comments and the two hash lines intact.
"""

# __FLEX_SIGNATURE_HASH__: 7e819b7d7752be8e8a124b2f01caf257fc79e7fa67ddd5ba677cb2bdb3924efd
# __FLEX_BODY_HASH__: 0206423835c8
# flex_id: SamePlace

import dspy


class SamePlaceModule(dspy.Module):
    """Standalone dspy.Module compiled from the SamePlace signature."""

    # __FLEX_PREDICTORS_BEGIN__
    PREDICTORS = {
        "judge": dspy.ChainOfThought(
            "input_name, input_address, match_name, match_address, distance: float -> is_same: bool"
        ),
    }
    # __FLEX_PREDICTORS_END__

    def __init__(self) -> None:
        super().__init__()
        for _name, _predictor in self.PREDICTORS.items():
            setattr(self, _name, _predictor)

    # __FLEX_FORWARD_BEGIN__
    def forward(self, **inputs):
        import re

        input_name = inputs.get("input_name", "") or ""
        input_address = inputs.get("input_address", "") or ""
        match_name = inputs.get("match_name", "") or ""
        match_address = inputs.get("match_address", "") or ""
        try:
            distance = float(inputs.get("distance", 0.0) or 0.0)
        except (TypeError, ValueError):
            distance = 0.0

        # NOTE: distance units appear to be in meters in the examples
        # (e.g. 5.77 meters for same-address pair, 278 for nearby different places,
        # 8.8 for very close different places). We'll treat distance in meters.

        def normalize(text):
            text = text.lower().strip()
            # Strip trailing store numbers like #72, # 72
            text = re.sub(r"#\s*\d+", " ", text)
            noise = [
                r"\b(inc|incorporated|llc|l\.l\.c\.|ltd|limited|co|corp|corporation|company)\b",
                r"\b(the|and|&)\b",
                r"\b(restaurant|cafe|bar|grill|shop|store|bakeshop|market|supermarket)\b",
            ]
            for pat in noise:
                text = re.sub(pat, " ", text)
            text = re.sub(r"[^\w\s]", " ", text)
            text = re.sub(r"\s+", " ", text).strip()
            return text

        def core_name(text):
            # Aggressive normalization: also strip digits
            n = normalize(text)
            n = re.sub(r"\b\d+\b", " ", n)
            n = re.sub(r"\s+", " ", n).strip()
            return n

        def tokens(text):
            return set(t for t in text.split() if t)

        def jaccard(a, b):
            if not a or not b:
                return 0.0
            return len(a & b) / len(a | b)

        def normalize_address(addr):
            addr = addr.lower().strip()
            repl = {
                r"\bstreet\b": "st",
                r"\bavenue\b": "ave",
                r"\bboulevard\b": "blvd",
                r"\broad\b": "rd",
                r"\bdrive\b": "dr",
                r"\blane\b": "ln",
                r"\bcourt\b": "ct",
                r"\bplace\b": "pl",
                r"\bsuite\b": "ste",
                r"\bnorth\b": "n",
                r"\bsouth\b": "s",
                r"\beast\b": "e",
                r"\bwest\b": "w",
            }
            for pat, sub in repl.items():
                addr = re.sub(pat, sub, addr)
            addr = re.sub(r"[^\w\s]", " ", addr)
            addr = re.sub(r"\s+", " ", addr).strip()
            return addr

        def extract_street_number(addr):
            m = re.match(r"^\s*(\d+)", addr)
            return m.group(1) if m else None

        def address_core(addr):
            # Drop unit/suite indicators at the end like "I", "A", "ste 100", etc.
            a = normalize_address(addr)
            # Remove trailing single-letter unit indicators
            a = re.sub(r"\s+[a-z]$", "", a)
            # Remove "ste <num>" or "unit <num>" or "apt <num>"
            a = re.sub(r"\b(ste|unit|apt)\s+\w+", " ", a)
            a = re.sub(r"\s+", " ", a).strip()
            return a

        name_a_norm = normalize(input_name)
        name_b_norm = normalize(match_name)
        core_a = core_name(input_name)
        core_b = core_name(match_name)

        addr_a_norm = address_core(input_address)
        addr_b_norm = address_core(match_address)

        name_tokens_a = tokens(name_a_norm)
        name_tokens_b = tokens(name_b_norm)
        name_sim = jaccard(name_tokens_a, name_tokens_b)
        name_exact = name_a_norm == name_b_norm and bool(name_a_norm)

        core_tokens_a = tokens(core_a)
        core_tokens_b = tokens(core_b)
        core_sim = jaccard(core_tokens_a, core_tokens_b)
        core_exact = core_a == core_b and bool(core_a)
        # Subset check: one core name's tokens are a subset of the other
        core_subset = (
            bool(core_tokens_a) and bool(core_tokens_b) and
            (core_tokens_a.issubset(core_tokens_b) or core_tokens_b.issubset(core_tokens_a))
        )

        addr_tokens_a = tokens(addr_a_norm)
        addr_tokens_b = tokens(addr_b_norm)
        addr_sim = jaccard(addr_tokens_a, addr_tokens_b)
        addr_exact = addr_a_norm == addr_b_norm and bool(addr_a_norm)

        num_a = extract_street_number(addr_a_norm)
        num_b = extract_street_number(addr_b_norm)
        street_num_match = (num_a is not None and num_b is not None and num_a == num_b)
        street_num_conflict = (num_a is not None and num_b is not None and num_a != num_b)

        # Distance thresholds in meters
        VERY_CLOSE = 20.0   # ~same building
        CLOSE = 50.0
        NEAR = 150.0
        FAR = 500.0

        # Deterministic decisions:

        # Same address (including same street number) + same/subset core name => same
        if addr_exact and (core_exact or core_subset or core_sim >= 0.5):
            return dspy.Prediction(is_same=True)

        # Very close + matching street number + name is exact or one is subset of other
        if distance <= VERY_CLOSE and street_num_match and (core_exact or core_subset):
            return dspy.Prediction(is_same=True)

        # Very close + matching street number + very high name similarity
        if distance <= CLOSE and street_num_match and core_sim >= 0.7:
            return dspy.Prediction(is_same=True)

        # Far apart => different
        if distance > FAR:
            return dspy.Prediction(is_same=False)

        # Conflicting street numbers and not extremely close => different
        if street_num_conflict and distance > VERY_CLOSE:
            return dspy.Prediction(is_same=False)

        # Very low name similarity and different addresses and not co-located => different
        if core_sim < 0.2 and not addr_exact and distance > VERY_CLOSE:
            return dspy.Prediction(is_same=False)

        # Ambiguous: ask the LM.
        judged = self.judge(
            input_name=input_name,
            input_address=input_address,
            match_name=match_name,
            match_address=match_address,
            distance=distance,
        )
        return dspy.Prediction(is_same=bool(judged.is_same))
    # __FLEX_FORWARD_END__
