"""Generated by dspy.Flex.

You may edit the PREDICTORS dict and the forward()
body between the marker comments below; dspy.Flex parses those regions back
out on the next run.

- __FLEX_SIGNATURE_HASH__ tracks the user's Signature. If you change the
  Signature, Flex regenerates this file, seeding the codegen LM with your
  current code.
- __FLEX_BODY_HASH__ tracks the code body. If you hand-edit the body, Flex
  detects it on the next run, honors your code, and refreshes this hash.

Leave the marker comments and the two hash lines intact.
"""

# __FLEX_SIGNATURE_HASH__: 2001b8047674f53abecf5194a2d0b2f20c5d132b88bb59c420ad74cd2d87798c
# __FLEX_BODY_HASH__: da386e9b9ba8
# flex_id: InvoiceTotal

import dspy


class InvoiceTotalModule(dspy.Module):
    """Standalone dspy.Module compiled from the InvoiceTotal signature."""

    # __FLEX_PREDICTORS_BEGIN__
    PREDICTORS = {
        "rlm": dspy.RLM("invoice: str -> total_cents: int"),
    }
    # __FLEX_PREDICTORS_END__

    def __init__(self) -> None:
        super().__init__()
        for _name, _predictor in self.PREDICTORS.items():
            setattr(self, _name, _predictor)

    # __FLEX_FORWARD_BEGIN__
    def forward(self, **inputs):
        result = self.rlm(**inputs)
        return dspy.Prediction(total_cents=result.total_cents)
    # __FLEX_FORWARD_END__
