"""Generated by dspy.Flex.

You may edit the PREDICTORS dict and the forward() body between the marker
comments below. dspy.Flex parses those regions back out.

- __FLEX_SIGNATURE_HASH__ tracks the user's Signature. If you change the
  Signature, Flex regenerates this file, seeding the codegen LM with your
  current code.
- __FLEX_BODY_HASH__ tracks the code body. If you hand-edit the body, Flex
  detects it on the next run, honors your code, and refreshes this hash.

Leave the marker comments and the two hash lines intact.
"""

# __FLEX_SIGNATURE_HASH__: 2001b8047674f53abecf5194a2d0b2f20c5d132b88bb59c420ad74cd2d87798c
# __FLEX_BODY_HASH__: 53f4bcc32f0d
# flex_id: InvoiceTotal

# __FLEX_PREDICTORS_BEGIN__
PREDICTORS = {
    # The LM does only what it's good at: pull the numbers out of the text.
    "extract": dspy.ChainOfThought(
        "invoice -> quantities: list[float], unit_prices_dollars: list[float], "
        "adjustments_dollars: list[float]"
    ),
}
# __FLEX_PREDICTORS_END__

# __FLEX_FORWARD_BEGIN__
def forward(self, **inputs):
    out = self.extract(invoice=inputs["invoice"])
    quantities = list(out.quantities or [])
    unit_prices = list(out.unit_prices_dollars or [])
    adjustments = list(out.adjustments_dollars or [])
    # Arithmetic lives in Python, not in the LM's head.
    line_total = sum(q * p for q, p in zip(quantities, unit_prices))
    total_dollars = line_total + sum(adjustments)
    total_cents = round(total_dollars * 100)
    return dspy.Prediction(total_cents=max(0, int(total_cents)))
# __FLEX_FORWARD_END__
