"""Generated by dspy.Flex.

You may edit the PREDICTORS dict and the forward() body between the marker
comments below. dspy.Flex parses those regions back out.

- __FLEX_SIGNATURE_HASH__ tracks the user's Signature. If you change the
  Signature, Flex regenerates this file, seeding the codegen LM with your
  current code.
- __FLEX_BODY_HASH__ tracks the code body. If you hand-edit the body, Flex
  detects it on the next run, honors your code, and refreshes this hash.

Leave the marker comments and the two hash lines intact.
"""

# __FLEX_SIGNATURE_HASH__: 62c09f2dfa8a4329f227a7ccadfe6e481b38c4ec7a7afe6eb141ee67b8da9ee7
# __FLEX_BODY_HASH__: 73195dd158c8
# flex_id: MathWord

# __FLEX_PREDICTORS_BEGIN__
PREDICTORS = {
    "extract_numbers": dspy.Predict("problem -> numbers"),
    "calculate_answer": dspy.ChainOfThought("numbers -> answer"),
}
# __FLEX_PREDICTORS_END__

# __FLEX_FORWARD_BEGIN__
def forward(self, **inputs):
    # Extract numbers from the problem statement
    numbers_result = self.extract_numbers(problem=inputs['problem'])
    # Calculate the answer using step-by-step reasoningggg
    answer_result = self.calculate_answer(numbers=numbers_result.numbers)
    # Convert the answer to an integer to ensure the output field matches the expected type
    answer_integer = int(answer_result.answer.split()[0])  # Assuming answer is in the format 'x units'
    return dspy.Prediction(answer=answer_integer)
# __FLEX_FORWARD_END__
