"""Generated by dspy.Flex.

You may edit the PREDICTORS dict and the forward()
body between the marker comments below; dspy.Flex parses those regions back
out on the next run.

- __FLEX_SIGNATURE_HASH__ tracks the user's Signature. If you change the
  Signature, Flex regenerates this file, seeding the codegen LM with your
  current code.
- __FLEX_BODY_HASH__ tracks the code body. If you hand-edit the body, Flex
  detects it on the next run, honors your code, and refreshes this hash.

Leave the marker comments and the two hash lines intact.
"""

# __FLEX_SIGNATURE_HASH__: 62c09f2dfa8a4329f227a7ccadfe6e481b38c4ec7a7afe6eb141ee67b8da9ee7
# __FLEX_BODY_HASH__: 58222ed70f12
# flex_id: MathWord

import dspy


class MathWordModule(dspy.Module):
    """Standalone dspy.Module compiled from the MathWord signature."""

    # __FLEX_PREDICTORS_BEGIN__
    PREDICTORS = {
        "rlm": dspy.RLM("problem: str -> answer: int"),
    }
    # __FLEX_PREDICTORS_END__

    def __init__(self) -> None:
        super().__init__()
        for _name, _predictor in self.PREDICTORS.items():
            setattr(self, _name, _predictor)

    # __FLEX_FORWARD_BEGIN__
    def forward(self, **inputs):
        result = self.rlm(**inputs)
        return dspy.Prediction(answer=result.answer)
    # __FLEX_FORWARD_END__
