"""Normalized language model implementations and types."""

from dspy.clients.language_models.base import LanguageModel, LMCapabilities
from dspy.clients.language_models.types import (
    Assistant,
    AsyncLMStream,
    Developer,
    LMAudioDelta,
    LMAudioPart,
    LMBasePart,
    LMCacheConfig,
    LMCitationDelta,
    LMCitationPart,
    LMConfig,
    LMDelta,
    LMFilePart,
    LMHistoryEntry,
    LMImageDelta,
    LMImagePart,
    LMMessage,
    LMOutput,
    LMOutputBuilder,
    LMPart,
    LMPromptCacheConfig,
    LMReasoningConfig,
    LMRefusalPart,
    LMRequest,
    LMResponse,
    LMStream,
    LMStreamDeltaEvent,
    LMStreamEndEvent,
    LMStreamErrorEvent,
    LMStreamEvent,
    LMStreamOutputEndEvent,
    LMStreamStartEvent,
    LMTextDelta,
    LMTextPart,
    LMThinkingDelta,
    LMThinkingPart,
    LMToolCallDelta,
    LMToolCallPart,
    LMToolChoice,
    LMToolResultPart,
    LMToolSpec,
    LMUsage,
    System,
    LMToolCall,
    ToolResult,
    User,
)

# Curated set of names promoted to the top-level `dspy.*` namespace.
# Everything in `__all__` (below) remains importable from `dspy.clients.language_models`
# (and via the `dspy.lm` re-export shim), but only this subset becomes `dspy.X`.
# Hybrid policy decision from the migration plan (commit 1).
TOP_LEVEL_EXPORTS = [
    "LanguageModel",
    "LMCapabilities",
    "LMRequest",
    "LMResponse",
    "LMMessage",
    "LMConfig",
    "LMUsage",
    "LMHistoryEntry",
    "System",
    "Developer",
    "User",
    "Assistant",
    "LMToolCall",
    "ToolResult",
]

__all__ = [
    "LanguageModel",
    "LMCapabilities",
    "LMBasePart",
    "LMTextPart",
    "LMImagePart",
    "LMAudioPart",
    "LMFilePart",
    "LMToolCallPart",
    "LMToolResultPart",
    "LMThinkingPart",
    "LMCitationPart",
    "LMRefusalPart",
    "LMPart",
    "LMMessage",
    "LMToolSpec",
    "LMReasoningConfig",
    "LMToolChoice",
    "LMCacheConfig",
    "LMPromptCacheConfig",
    "LMConfig",
    "LMRequest",
    "LMUsage",
    "LMOutput",
    "LMResponse",
    "LMDelta",
    "LMTextDelta",
    "LMThinkingDelta",
    "LMToolCallDelta",
    "LMCitationDelta",
    "LMImageDelta",
    "LMAudioDelta",
    "LMStreamEvent",
    "LMStreamStartEvent",
    "LMStreamDeltaEvent",
    "LMStreamOutputEndEvent",
    "LMStreamEndEvent",
    "LMStreamErrorEvent",
    "LMOutputBuilder",
    "LMStream",
    "AsyncLMStream",
    "LMHistoryEntry",
    "System",
    "Developer",
    "User",
    "Assistant",
    "LMToolCall",
    "ToolResult",
]
