from .gsm8k import GSM8KTask
from .hotpotqa import HotPotQATask
from .scone import ScoNeTask
from .tweet import TweetTask
from .tweet_metric import TweetMetricTask
from .heart_disease import HeartDiseaseTask
from .hotpotqa_conditional import HotPotQAConditionalTask
from .hover import HoverRetrieveDiscrete
from .iris_typo import IrisTypoClassifierTask
from .iris import IrisClassifierTask