from .predict import Predict
from .chain_of_thought import ChainOfThought
from .multi_chain_comparison import MultiChainComparison
from .chain_of_thought_with_hint import ChainOfThoughtWithHint
from .react import ReAct
from .aggregation import majority
from .program_of_thought import ProgramOfThought
from .retry import Retry
from .knn import KNN