from __future__ import annotations

import hashlib
import json
import logging
import textwrap
import types
from pathlib import Path
from typing import Any

import dspy
from dspy.flex.codegen import FlexContext, generate
from dspy.flex.exploration import ExplorationStore, FlexEvent, candidate_id
from dspy.flex.manifest import ManifestStore
from dspy.primitives.module import Module
from dspy.utils.annotation import experimental

logger = logging.getLogger(__name__)


def _exec_source(source: str, context_names: dict[str, Any] | None = None) -> dict[str, Any]:
    code = compile(source, filename="<flex>", mode="exec")
    globals_ns: dict[str, Any] = dict(context_names or {})
    exec(code, globals_ns)
    return globals_ns


_GENERATED_FILE_HEADER = '''"""Generated by dspy.Flex.

You may edit the PREDICTORS dict and the forward() body between the marker
comments below. dspy.Flex parses those regions back out.

- __FLEX_SIGNATURE_HASH__ tracks the user's Signature. If you change the
  Signature, Flex regenerates this file -- seeding the codegen LM with your
  current code.
- __FLEX_BODY_HASH__ tracks the code body. If you hand-edit the body, Flex
  detects it on the next run, honors your code, and refreshes this hash.

Leave the marker comments and the two hash lines intact.
"""
'''


@experimental(version="3.3.0b2")
class Flex(Module):
    """A DSPy Module whose ``forward()`` body is authored by an LM from a Signature.

    Args:
        signature: A ``dspy.Signature`` class (or string) declaring inputs/outputs.
        persist_to: Path to a checked-in ``.py`` file holding the generated code.
            When set, the file is loaded if its signature hash matches; otherwise
            it is (re-)generated and written. When None, the implementation lives
            only in memory.
        context: Optional list of ``dspy.Tool`` / callables / style note strings to
            inject into codegen and into the runtime exec namespace.
        codegen_lm: LM to use for generation. Defaults to ``dspy.settings.lm``.
        flex_id: Stable identifier in the manifest. Defaults to the Signature class
            name (or a hash of the signature when ``persist_to`` is None).

    Persistence layout: when ``persist_to`` is set, the generated source goes
    to that file and bookkeeping goes to ``<persist_to>.parent/.flex/`` —
    ``manifest.json`` (shared across all Flexes in that directory) and per-flex
    history under ``.flex/<flex_id>/``. When ``persist_to=None`` the
    implementation lives only in memory and no bookkeeping is written.
    """

    def __init__(
        self,
        signature: Any,
        *,
        persist_to: str | Path | None = None,
        context: list[Any] | None = None,
        codegen_lm: dspy.LM | None = None,
        flex_id: str | None = None,
    ):
        super().__init__()

        from dspy.signatures.signature import ensure_signature

        self._signature_cls = ensure_signature(signature)
        self._persist_to: Path | None = Path(persist_to) if persist_to else None
        self._codegen_lm = codegen_lm

        style_notes: list[str] = []
        tools: list[Any] = []
        for item in context or []:
            if isinstance(item, str):
                style_notes.append(item)
            else:
                tools.append(item)
        self._flex_ctx = FlexContext(
            signature_cls=self._signature_cls, tools=tools, style_notes=style_notes
        )

        self._forward_src: str | None = None
        self._predictors_src: str | None = None
        self._predictor_names: list[str] = []

        sig_hash = self._signature_hash()
        self._flex_id = flex_id or getattr(self._signature_cls, "__name__", None) or f"flex_{sig_hash[:8]}"

        # `.flex/` always lives next to `persist_to`. In-memory mode (no
        # persist_to) → root=None → the store no-ops on every write.
        flex_root = self._persist_to.parent if self._persist_to is not None else None
        self._flex_root: Path | None = flex_root
        self._exploration = ExplorationStore(flex_root, self._flex_id)

        self._lazy_implement()

    def implement(self, *, force: bool = False) -> None:
        """Explicitly (re-)generate the implementation."""
        if force:
            self._predictors_src = None
            self._forward_src = None
        self._lazy_implement(force=force)

    @property
    def signature(self) -> Any:
        return self._signature_cls

    @property
    def predictors_src(self) -> str | None:
        return self._predictors_src

    @property
    def forward_src(self) -> str | None:
        return self._forward_src

    def dump_state(self, json_mode: bool = True) -> dict[str, Any]:
        state = super().dump_state(json_mode=json_mode)
        state["_flex"] = {
            "forward_src": self._forward_src,
            "predictors_src": self._predictors_src,
            "signature_hash": self._signature_hash(),
            "flex_id": self._flex_id,
        }
        return state

    def load_state(self, state: dict[str, Any], *, allow_unsafe_lm_state: bool = False) -> None:
        flex_state = state.pop("_flex", None) if isinstance(state, dict) else None
        if flex_state and flex_state.get("forward_src") and flex_state.get("predictors_src"):
            self._bind_code(flex_state["predictors_src"], flex_state["forward_src"])
        if state:
            super().load_state(state, allow_unsafe_lm_state=allow_unsafe_lm_state)

    def _lazy_implement(self, *, force: bool = False) -> None:
        if self._forward_src and self._predictors_src and not force:
            return

        sig_hash = self._signature_hash()

        # Seed for regeneration: the current on-disk body, carried into codegen
        # when the signature changed so hand edits aren't thrown away.
        seed: tuple[str, str] | None = None

        if self._persist_to and self._persist_to.exists() and not force:
            stored = self._read_persisted()
            if stored is not None:
                body_id = candidate_id(stored["predictors_src"], stored["forward_src"])
                body_edited = stored["body_hash"] is not None and body_id != stored["body_hash"]

                if stored["signature_hash"] == sig_hash:
                    # Signature unchanged — run exactly what's on disk, edited or not.
                    self._bind_code(stored["predictors_src"], stored["forward_src"])
                    if body_edited:
                        self._honor_manual_edit(stored, sig_hash, body_id)
                    else:
                        self._exploration.record(
                            FlexEvent.LOAD,
                            predictors_src=stored["predictors_src"],
                            forward_src=stored["forward_src"],
                            signature_hash=sig_hash,
                            extra={"source_path": str(self._persist_to)},
                        )
                        logger.info(
                            "dspy.Flex %r: loaded existing implementation from %s",
                            self._flex_id,
                            self._persist_to,
                        )
                        # Legacy file written before body hashes existed: backfill
                        # one so future edits are detectable.
                        if stored["body_hash"] is None:
                            self._write_persisted(stored["predictors_src"], stored["forward_src"], sig_hash)
                    return

                # Signature changed — regenerate, seeded from the current body.
                seed = (stored["predictors_src"], stored["forward_src"])
                if body_edited:
                    # Preserve the hand edit in the ledger so the codegen event's
                    # parent (the seed) refers to a real candidate.
                    self._exploration.record(
                        FlexEvent.MANUAL_EDIT,
                        predictors_src=stored["predictors_src"],
                        forward_src=stored["forward_src"],
                        signature_hash=stored["signature_hash"],
                        extra={
                            "source_path": str(self._persist_to),
                            "reason": "manual edit seeding regeneration",
                        },
                    )
                logger.info(
                    "dspy.Flex %r: signature hash mismatch on %s — regenerating from %s implementation.",
                    self._flex_id,
                    self._persist_to,
                    "hand-edited" if body_edited else "previous",
                )

        predictors_src, forward_src = generate(self._flex_ctx, lm=self._codegen_lm, seed=seed)
        self._bind_code(predictors_src, forward_src)
        seed_parents = [candidate_id(*seed)] if seed is not None else None
        cid = self._exploration.record(
            FlexEvent.CODEGEN,
            predictors_src=predictors_src,
            forward_src=forward_src,
            signature_hash=sig_hash,
            parents=seed_parents,
        )

        if self._persist_to is not None:
            self._write_persisted(predictors_src, forward_src, sig_hash)
            assert self._flex_root is not None
            manifest = ManifestStore(self._flex_root)
            version_id = manifest.append_version(
                flex_id=self._flex_id,
                src_path=self._persist_to,
                signature_hash=sig_hash,
                candidate_id=cid,
                parents=seed_parents,
                notes="regenerated from seed (signature changed)" if seed is not None else "initial codegen",
            )
            self._exploration.record(
                FlexEvent.ACCEPT,
                predictors_src=predictors_src,
                forward_src=forward_src,
                signature_hash=sig_hash,
                extra={"version_id": version_id, "src_path": str(self._persist_to)},
            )
            logger.info("dspy.Flex %r: wrote new implementation to %s", self._flex_id, self._persist_to)
        else:
            logger.warning(
                "dspy.Flex %r: persist_to=None — implementation is in-memory only and will be "
                "regenerated next process start. Set persist_to= for production.",
                self._flex_id,
            )

    def _honor_manual_edit(self, stored: dict[str, Any], sig_hash: str, body_id: str) -> None:
        """Accept a hand-edited file: record it, refresh the body hash, and version it.

        Called when the signature is unchanged but the body hash no longer matches
        the persisted code — i.e. the user edited the file by hand. The edit is the
        running implementation (already bound by the caller). We log a
        ``manual_edit`` event, rewrite the file so its body hash
        matches again, and append a manifest version.
        """
        self._exploration.record(
            FlexEvent.MANUAL_EDIT,
            predictors_src=stored["predictors_src"],
            forward_src=stored["forward_src"],
            signature_hash=sig_hash,
            extra={"source_path": str(self._persist_to)},
        )
        # Refresh the body hash so subsequent runs see a pristine file.
        self._write_persisted(stored["predictors_src"], stored["forward_src"], sig_hash)

        if self._flex_root is not None:
            manifest = ManifestStore(self._flex_root)
            prev = manifest.latest(self._flex_id)
            parents = [prev["candidate_id"]] if prev and prev.get("candidate_id") else []
            version_id = manifest.append_version(
                flex_id=self._flex_id,
                src_path=self._persist_to,
                signature_hash=sig_hash,
                candidate_id=body_id,
                parents=parents,
                notes="manual edit",
            )
            self._exploration.record(
                FlexEvent.ACCEPT,
                predictors_src=stored["predictors_src"],
                forward_src=stored["forward_src"],
                signature_hash=sig_hash,
                extra={"version_id": version_id, "src_path": str(self._persist_to)},
            )
        logger.info(
            "dspy.Flex %r: honored hand-edited implementation in %s (recorded a `manual_edit` "
            "event and a new manifest version).",
            self._flex_id,
            self._persist_to,
        )

    def _bind_code(self, predictors_src: str, forward_src: str) -> None:
        """Exec and attach both source artifacts to ``self``."""
        ctx_names = self._flex_ctx.context_names()
        ctx_names["dspy"] = dspy

        for old_name in self._predictor_names:
            if hasattr(self, old_name):
                delattr(self, old_name)
        self._predictor_names = []

        pred_ns = _exec_source(predictors_src, context_names=ctx_names)
        predictors = pred_ns.get("PREDICTORS")
        if not isinstance(predictors, dict):
            raise RuntimeError("predictors_src must define a `PREDICTORS = {...}` dict at module scope")
        for name, predictor in predictors.items():
            if not isinstance(name, str) or not name.isidentifier():
                raise RuntimeError(f"PREDICTORS key {name!r} is not a valid Python identifier")
            setattr(self, name, predictor)
            self._predictor_names.append(name)

        fwd_ns = _exec_source(forward_src, context_names=ctx_names)
        forward_fn = fwd_ns.get("forward")
        if not callable(forward_fn):
            raise RuntimeError("forward_src must define a `def forward(self, ...)` function")
        self.forward = types.MethodType(forward_fn, self)

        self._predictors_src = predictors_src
        self._forward_src = forward_src

    def _read_persisted(self) -> dict[str, Any] | None:
        if self._persist_to is None or not self._persist_to.exists():
            return None
        text = self._persist_to.read_text(encoding="utf-8")
        marker_hash = "# __FLEX_SIGNATURE_HASH__:"
        marker_body_hash = "# __FLEX_BODY_HASH__:"
        marker_pred_start = "# __FLEX_PREDICTORS_BEGIN__"
        marker_pred_end = "# __FLEX_PREDICTORS_END__"
        marker_fwd_start = "# __FLEX_FORWARD_BEGIN__"
        marker_fwd_end = "# __FLEX_FORWARD_END__"

        try:
            sig_hash = text.split(marker_hash, 1)[1].splitlines()[0].strip()
            predictors_src = text.split(marker_pred_start, 1)[1].split(marker_pred_end, 1)[0]
            forward_src = text.split(marker_fwd_start, 1)[1].split(marker_fwd_end, 1)[0]
        except IndexError:
            logger.warning("dspy.Flex %r: persisted file at %s is missing expected markers", self._flex_id, self._persist_to)
            return None

        body_hash: str | None = None
        if marker_body_hash in text:
            body_hash = text.split(marker_body_hash, 1)[1].splitlines()[0].strip() or None

        return {
            "signature_hash": sig_hash,
            "body_hash": body_hash,
            "predictors_src": textwrap.dedent(predictors_src).strip("\n"),
            "forward_src": textwrap.dedent(forward_src).strip("\n"),
        }

    def _write_persisted(self, predictors_src: str, forward_src: str, sig_hash: str) -> None:
        assert self._persist_to is not None
        self._persist_to.parent.mkdir(parents=True, exist_ok=True)
        body_hash = candidate_id(predictors_src, forward_src)
        body = (
            _GENERATED_FILE_HEADER
            + f"\n# __FLEX_SIGNATURE_HASH__: {sig_hash}\n"
            + f"# __FLEX_BODY_HASH__: {body_hash}\n"
            + f"# flex_id: {self._flex_id}\n\n"
            + "# __FLEX_PREDICTORS_BEGIN__\n"
            + predictors_src.rstrip("\n")
            + "\n# __FLEX_PREDICTORS_END__\n\n"
            + "# __FLEX_FORWARD_BEGIN__\n"
            + forward_src.rstrip("\n")
            + "\n# __FLEX_FORWARD_END__\n"
        )
        self._persist_to.write_text(body, encoding="utf-8")

    def _signature_hash(self) -> str:
        cls: Any = self._signature_cls
        canonical = {
            "name": getattr(cls, "__name__", ""),
            "instructions": getattr(cls, "instructions", "") or "",
            "input_fields": [
                (n, _annotation_repr(f.annotation)) for n, f in cls.input_fields.items()
            ],
            "output_fields": [
                (n, _annotation_repr(f.annotation)) for n, f in cls.output_fields.items()
            ],
        }
        blob = json.dumps(canonical, sort_keys=True).encode("utf-8")
        return hashlib.sha256(blob).hexdigest()


def _annotation_repr(t: Any) -> str:
    if t is None:
        return "None"
    name = getattr(t, "__name__", None)
    if name:
        return name
    return str(t).replace("typing.", "")
