from __future__ import annotations

import textwrap
from typing import NamedTuple

_SIG_HASH_PREFIX = "# __FLEX_SIGNATURE_HASH__:"
_BODY_HASH_PREFIX = "# __FLEX_BODY_HASH__:"
_FLEX_ID_PREFIX = "# flex_id:"
_PREDICTORS_BEGIN = "# __FLEX_PREDICTORS_BEGIN__"
_PREDICTORS_END = "# __FLEX_PREDICTORS_END__"
_FORWARD_BEGIN = "# __FLEX_FORWARD_BEGIN__"
_FORWARD_END = "# __FLEX_FORWARD_END__"
_CLASS_INDENT = "    "

_FILE_HEADER_DOCSTRING = '''"""Generated by dspy.Flex.

You may edit the PREDICTORS dict and the forward()
body between the marker comments below; dspy.Flex parses those regions back
out on the next run.

- __FLEX_SIGNATURE_HASH__ tracks the user's Signature. If you change the
  Signature, Flex regenerates this file, seeding the codegen LM with your
  current code.
- __FLEX_BODY_HASH__ tracks the code body. If you hand-edit the body, Flex
  detects it on the next run, honors your code, and refreshes this hash.

Leave the marker comments and the two hash lines intact.
"""
'''


class PersistedFlex(NamedTuple):
    """Parsed view of a persisted Flex module file."""

    signature_hash: str
    body_hash: str | None
    predictors_src: str
    forward_src: str


def render_persisted_file(
    *,
    signature_hash: str,
    body_hash: str,
    flex_id: str,
    signature_name: str,
    predictors_src: str,
    forward_src: str,
) -> str:
    """Render a complete Flex module file."""
    module_name = f"{signature_name}Module"
    predictors_block = _wrap_with_markers(predictors_src, _PREDICTORS_BEGIN, _PREDICTORS_END)
    forward_block = _wrap_with_markers(forward_src, _FORWARD_BEGIN, _FORWARD_END)

    return (
        _FILE_HEADER_DOCSTRING
        + f"\n{_SIG_HASH_PREFIX} {signature_hash}\n"
        + f"{_BODY_HASH_PREFIX} {body_hash}\n"
        + f"{_FLEX_ID_PREFIX} {flex_id}\n\n"
        + "import dspy\n\n\n"
        + f"class {module_name}(dspy.Module):\n"
        + f'    """Standalone dspy.Module compiled from the {signature_name} signature."""\n'
        + "\n"
        + predictors_block
        + "\n\n"
        + "    def __init__(self) -> None:\n"
        + "        super().__init__()\n"
        + "        for _name, _predictor in self.PREDICTORS.items():\n"
        + "            setattr(self, _name, _predictor)\n"
        + "\n"
        + forward_block
        + "\n"
    )


def parse_persisted_file(text: str) -> PersistedFlex | None:
    """Extract hashes and source regions from a Flex file."""
    try:
        signature_hash = text.split(_SIG_HASH_PREFIX, 1)[1].splitlines()[0].strip()
        predictors_raw = text.split(_PREDICTORS_BEGIN, 1)[1].split(_PREDICTORS_END, 1)[0]
        forward_raw = text.split(_FORWARD_BEGIN, 1)[1].split(_FORWARD_END, 1)[0]
    except IndexError:
        return None

    body_hash: str | None = None
    if _BODY_HASH_PREFIX in text:
        body_hash = text.split(_BODY_HASH_PREFIX, 1)[1].splitlines()[0].strip() or None

    return PersistedFlex(
        signature_hash=signature_hash,
        body_hash=body_hash,
        predictors_src=textwrap.dedent(predictors_raw).strip("\n"),
        forward_src=textwrap.dedent(forward_raw).strip("\n"),
    )


def _wrap_with_markers(src: str, begin: str, end: str) -> str:
    """Wrap a module-scope source string with markers, indented for class scope."""
    return textwrap.indent(f"{begin}\n{src.strip()}\n{end}", _CLASS_INDENT)
