"""
lm15.protocols — Protocol definitions for provider LMs and sessions.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Any, Iterator, Protocol

from .features import EndpointSupport, ProviderManifest
from .models import ModelInfo
from .types import (
    CachedPrefix,
    CacheInfo,
    CachePage,
    VideoGenerationRequest,
    VideoJobInfo,
    VideoPart,
    SpeechGenerationRequest,
    SpeechGenerationResponse,
    BatchRequest,
    BatchEntry,
    BatchJobInfo,
    FileInfo,
    FilePage,
    FileUploadRequest,
    ImageGenerationRequest,
    ImageGenerationResponse,
    LiveClientEvent,
    LiveConfig,
    LiveServerEvent,
    PartInput,
    Request,
    Response,
    StreamEvent,
)



class LiveSession(Protocol):
    def send(self, event: LiveClientEvent | None = None, **kwargs: Any) -> None: ...
    def send_turn(self, content: PartInput, *, turn_complete: bool = True) -> None: ...
    def send_audio(self, data: bytes | str, *, media_type: str = "audio/pcm;rate=16000") -> None: ...
    def send_image(self, data: bytes | str, *, media_type: str = "image/jpeg") -> None: ...
    def send_text(self, text: str) -> None: ...
    def send_tool_result(self, results: dict[str, Any]) -> None: ...
    def interrupt(self) -> None: ...
    def end_audio(self) -> None: ...
    def recv(self) -> LiveServerEvent: ...
    def close(self) -> None: ...


class ProviderLM(Protocol):
    provider: str
    supports: EndpointSupport
    manifest: ProviderManifest

    def complete(self, request: Request) -> Response: ...
    def stream(self, request: Request) -> Iterator[StreamEvent]: ...
    def live(self, config: LiveConfig) -> LiveSession: ...
    def file_upload(self, request: FileUploadRequest) -> FileInfo: ...
    def file_get(self, file_id: str) -> FileInfo: ...
    def file_list(self, limit: int = 20, cursor: str | None = None) -> FilePage: ...
    def file_delete(self, file_id: str) -> None: ...
    def file_download(self, file_id: str) -> bytes: ...
    def file_wait_ready(self, file_id: str, poll_every: float = 2.0, timeout: float | None = None) -> FileInfo: ...
    def batch_submit(self, request: BatchRequest) -> BatchJobInfo: ...
    def batch_status(self, batch_id: str) -> BatchJobInfo: ...
    def batch_results(self, batch_id: str) -> tuple[BatchEntry, ...]: ...
    def batch_cancel(self, batch_id: str) -> BatchJobInfo: ...
    def batch_list(self, limit: int = 20) -> tuple[BatchJobInfo, ...]: ...
    def image_generate(self, request: ImageGenerationRequest) -> ImageGenerationResponse: ...
    def speech_generate(self, request: SpeechGenerationRequest) -> SpeechGenerationResponse: ...
    def video_submit(self, request: VideoGenerationRequest) -> VideoJobInfo: ...
    def video_status(self, video_id: str) -> VideoJobInfo: ...
    def video_result(self, video_id: str) -> VideoPart: ...
    def video_list(self, limit: int = 20, model: str | None = None) -> tuple[VideoJobInfo, ...]: ...
    def list_models(self) -> tuple[ModelInfo, ...]: ...
    def cache_create(self, prefix: Request, *, ttl_seconds: int | None = None, label: str | None = None) -> CacheInfo: ...
    def cache_get(self, cache_id: str) -> CacheInfo: ...
    def cache_list(self, limit: int = 20, cursor: str | None = None) -> CachePage: ...
    def cache_delete(self, cache_id: str) -> None: ...
    def cache_update(self, cache_id: str, *, ttl_seconds: int) -> CacheInfo: ...
    def cache(self, prefix: Request, *, ttl_seconds: int | None = None, label: str | None = None) -> CachedPrefix: ...
